### ISSUE TITLE
AttributeError: 'SlaveController' object has no attribute 'slaveoutput'

### ISSUE THREAD

**Issue by ionelmc** [davehunt/pytest-html#21]
I got this weird error with 1.6:
```
Traceback (most recent call last):
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/main.py", line 84, in wrap_session
    doit(config, session)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/main.py", line 122, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/xdist/dsession.py", line 521, in pytest_runtestloop
    self.loop_once()
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/xdist/dsession.py", line 539, in loop_once
    call(**kwargs)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/xdist/dsession.py", line 582, in slave_errordown
    self.config.hook.pytest_testnodedown(node=node, error=error)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/pytest_html/plugin.py", line 61, in pytest_testnodedown
    node.config._environment = node.slaveoutput['environment']
AttributeError: 'SlaveController' object has no attribute 'slaveoutput'

```

Any idea what's going on?

**Comment by davehunt** [comment]
It could be that you don't have `pytest-xdist` installed. It shouldn't be required, but I thought `pytest_testnodedown` was only called if it was. We may be able to just guard against this by checking for this attribute before https://github.com/davehunt/pytest-html/blob/master/pytest_html/plugin.py#L61 like we do at https://github.com/davehunt/pytest-html/blob/master/pytest_html/plugin.py#L53

**Comment by The-Compiler** [comment]
This is odd - `pytest_testnodedown` is indeed defined in xdist's [`newhooks.py`](https://bitbucket.org/pytest-dev/pytest-xdist/src/8e1f81f8113ad87c9fab6ac346e8e71ecd2dc1ad/xdist/newhooks.py?at=default&fileviewer=file-view-default), and `SlaveController` is a [class from xdist](https://bitbucket.org/pytest-dev/pytest-xdist/src/8e1f81f8113ad87c9fab6ac346e8e71ecd2dc1ad/xdist/slavemanage.py?at=default&fileviewer=file-view-default#slavemanage.py-190) as well.

**Comment by ionelmc** [comment]
I'm pretty sure I had xdist installed. Might be something else?

**Comment by The-Compiler** [comment]
From xdist:

```python
class SlaveController(object):

    ...

    def process_from_remote(self, eventcall):
        """ this gets called for each object we receive from
            the other side and if the channel closes.

            Note that channel callbacks run in the receiver
            thread of execnet gateways - we need to
            avoid raising exceptions or doing heavy work.
        """
        try:
            ...
            elif eventname == "slavefinished":
                self._down = True
                self.slaveoutput = kwargs['slaveoutput']
                self.notify_inproc("slavefinished", node=self)
            ...
```

So I think `SlaveController` not having `slaveoutput` means the slave never finished properly?

I'm guessing this happens when the slave crashes in some way, so I guess checking for that attribute is the way to go.

**Comment by ionelmc** [comment]
Well, I did have some other failures in that jenkins build ... sounds like that might be the problem.

**Comment by RonnyPfannschmidt** [comment]
one can acceptance test for this with a unittest that calls os._exit(0)
i think it should be solved from the xdist side as well (better docs about the node object state)

**Comment by davehunt** [comment]
Fix has been reverted due to issues with pytest 2.8.x and Python 2.x

**Comment by davehunt** [comment]
I relanded but xfailed the problematic test.
