### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by The-Compiler** [davehunt/pytest-html#3]
What's the state of Python3 support with `pytest-html`?

In `html/plugin.py` I noticed this:

```python
# Python 2.X and 3.X compatibility
if sys.version_info[0] < 3:
    from codecs import open
```

However python3 tests were removed in 30a37b7b4ddb06db36659dd7c22740030fe9ca8d and it doesn't seem to work - one reason seems to be the `html` package name conflicts with the [html module in the stdlib](https://docs.python.org/3/library/html.html):

```
Downloading/unpacking pytest-html
  Downloading pytest-html-1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-v2gumy9z/pytest-html/setup.py) egg_info for package pytest-html
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/home/florian/proj/qutebrowser/git/.tox/unittests/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/home/florian/proj/qutebrowser/git/.tox/unittests/lib/python3.4/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/home/florian/proj/qutebrowser/git/.tox/unittests/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>
        from setuptools.depends import Require
      File "/home/florian/proj/qutebrowser/git/.tox/unittests/lib/python3.4/site-packages/setuptools/depends.py", line 6, in <module>
        from setuptools import compat
      File "/home/florian/proj/qutebrowser/git/.tox/unittests/lib/python3.4/site-packages/setuptools/compat.py", line 44, in <module>
        from html.entities import name2codepoint
    ImportError: No module named 'html.entities'
```

Would a pull request for python3 support be welcome? Then I'd like to get this working - it'll mean the package needs to be renamed however, e.g. to `pytest_html`.

Also, would it be okay to introduce [six](https://pypi.python.org/pypi/six) as a dependency if it makes things easier?

**Comment by davehunt** [comment]
A pull request would certainly be welcome! I had hoped for Python 3 support out of the box, but as we're still using python 2.7, I kind of gave up at the first sign of problems! :smile:

The package name makes more sense as `pytest_html`, so let's go for that!

As for the extra dependency, I'd prefer to avoid this if possible. This is just a small package so I'm guessing it won't be too hard for someone familiar with Python 3. That said, if six is a lightweight dependency and makes it much easier to be compatible then I'm happy to review a patch with this included.

**Comment by davehunt** [comment]
Of course, please also restore the Travis tests for Python 3 in your patch.

**Comment by davehunt** [comment]
Done via pull #4
