### ISSUE TITLE
TestHTML.test_environment_xdist_reruns does weird stuff

### ISSUE THREAD

**Issue by The-Compiler** [davehunt/pytest-html#31]
When doing `tox -e py27` locally, `TestHTML.test_environment_xdist_reruns` hangs for about a minute, eats 10 GB of RAM, and then fails with 12000 lines of output:

```
=================================== FAILURES ===================================
____________________ TestHTML.test_environment_xdist_reruns ____________________

self = <test_pytest_html.TestHTML instance at 0x7fab1c54ba28>
testdir = <Testdir local('/tmp/pytest-of-florian/pytest-12/testdir/test_environment_xdist_reruns0')>

    def test_environment_xdist_reruns(self, testdir):
        content = str(random.random())
        testdir.makeconftest("""
                import pytest
                @pytest.fixture(autouse=True)
                def _environment(request):
                    for i in range(2):
                        request.config._environment.append(('content', '{0}'))
            """.format(content))
        testdir.makepyfile('def test_fail(): assert False')
        result, html = run(testdir, 'report.html', '-n', '1', '--reruns', '1')
        assert result.ret
>       assert 'Environment' in html
E       assert 'Environment' in '<!DOCTYPE html><html>\n  <head>\n    <meta charset="utf-8"/>\n    <title>Test Report</title>\n    <style>body {\n\tfo...ation</th>\n          <th>Links</th></tr></thead>\n      <tbody id="results-table-body"></tbody></table></body></html>'

/home/florian/proj/pytest-html/test_pytest_html.py:322: AssertionError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /tmp/pytest-of-florian/pytest-12/testdir/test_environment_xdist_reruns0, inifile: 
plugins: rerunfailures-0.05, xdist-1.13.1, html-1.7
gw0 I
[gw0] node down: Traceback (most recent call last):
  File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 841, in _local_receive
    data = loads_internal(data, channel, strconfig)
  File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1350, in loads_internal
    return Unserializer(io, channelfactory, strconfig).load()
  File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1152, in load
    opcode = self.stream.read(1)
  File "/usr/lib/python2.7/StringIO.py", line 127, in read
    _complain_ifclosed(self.closed)
TypeError: 'NoneType' object is not callable

Replacing crashed slave gw0
[gw1] node down: Traceback (most recent call last):

[...]

Replacing crashed slave gw288
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/xdist/dsession.py", line 521, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/xdist/dsession.py", line 539, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/xdist/dsession.py", line 603, in slave_errordown
INTERNALERROR>     self._clone_node(node)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/xdist/dsession.py", line 665, in _clone_node
INTERNALERROR>     node = self.nodemanager.setup_node(spec, self.queue.put)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/xdist/slavemanage.py", line 49, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/multi.py", line 127, in makegateway
INTERNALERROR>     io = gateway_io.create_io(spec, execmodel=self.execmodel)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_io.py", line 113, in create_io
INTERNALERROR>     return Popen2IOMaster(args, execmodel)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_io.py", line 17, in __init__
INTERNALERROR>     self.popen = p = execmodel.PopenPiped(args)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 178, in PopenPiped
INTERNALERROR>     return self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)
INTERNALERROR>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
INTERNALERROR>     errread, errwrite)
INTERNALERROR>   File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
INTERNALERROR>     self.pid = os.fork()
INTERNALERROR> OSError: [Errno 12] Cannot allocate memory

======================== no tests ran in 80.46 seconds =========================
----------------------------- Captured stderr call -----------------------------
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 120, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 129, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 565, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 77, in pytest_collection_finish
INTERNALERROR>   File "<remote exec>", line 23, in sendevent
INTERNALERROR>   File "/home/florian/proj/pytest-html/.tox/py27/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 716, in send
INTERNALERROR>     raise IOError("cannot send to %r" % (self,))
INTERNALERROR> IOError: cannot send to <Channel id=1 closed>
[...]
```

@ronny @nicoddemus @bobsilverberg any idea what's going on here? I'm not familiar with xdist/execnet at all. The test source is here:

https://github.com/davehunt/pytest-html/blob/master/test_pytest_html.py#L310-L323

**Comment by The-Compiler** [comment]
Seems like this is a `pytest-rerunfailures` issue, I can reproduce this with their testsuite.

Opened here instead: https://github.com/gocept/pytest-rerunfailures/issues/24

**Comment by The-Compiler** [comment]
Err, of course I meant @RonnyPfannschmidt (who is `ronny` on Freenode) - sorry @ronny!
